<footer class="fabrx-footer pt-3 pt-md-5" id="footer">
  <div class="container">
    <div class="row pb-4 pt-2">
      <div class="col-2 text-center text-sm-start">
        <a href="<?=url_pesquisa("")?>">
          <img src="<?= url("assets/images/logo/logo_color.png") ?>" id="logo-footer" class="img-fluid" alt="U">
        </a>
      </div>
      <div class="col-10">
        <div class="fabrx-social text-center text-md-right mt-3 mt-sm-0 float-end">
          <a href="https://www.linkedin.com/in/cyro-gondim-33168511b/" class="text-decoration-none" style="font-size: 30px">
<!--              <svg id="Icon_Social_OutlineLinkedin" data-name="Icon/Social/OutlineLinkedin" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">-->
<!--                  <path data-name="Icon Color" d="M3.525,20.475a11.985,11.985,0,1,1,16.95-16.95,11.985,11.985,0,1,1-16.95,16.95ZM1.5,12A10.5,10.5,0,1,0,12,1.5,10.512,10.512,0,0,0,1.5,12Zm11.659,4.543H10.8c0-.051.031-6.446,0-7.113H13.16v1.008l-.006.009s-.006.009-.009.014h.015v-.023a2.325,2.325,0,0,1,2.126-1.175c1.7,0,2.714,1.2,2.714,3.2v4.078H15.643V12.737c0-1.052-.413-1.608-1.2-1.608a1.314,1.314,0,0,0-1.21.865,1.553,1.553,0,0,0-.078.576v3.973h0Zm-3.662,0H7.141V9.429H9.5v7.112h0ZM8.3,8.458A1.232,1.232,0,1,1,8.335,6,1.233,1.233,0,1,1,8.32,8.458Z" fill="#3f3b3b"></path>-->
<!--              </svg>-->
              <i class="fa-brands fa-linkedin"></i>
          </a>
          <a href="https://www.instagram.com/cyrogondim.corretor/" class="text-decoration-none" style="font-size: 30px">
              <i class="fa-brands fa-instagram"></i>
          </a>
        </div>
      </div>
    </div>
    <hr>
    <div class="container text-center">
      <span class="text-secondary ms-2">© 2022 Stark House</span>
    </div>
  </div>
</footer>