<footer class="fabrx-footer pt-3 pt-md-5" id="footer">
  <div class="container">
    <div class="row pb-4 pt-2">
      <div class="col-2 text-center text-sm-start">
        <a href="<?=url_pesquisa("")?>">
          <img src="<?= url("assets/images/logo/logo_color.png") ?>" id="logo-footer" class="img-fluid" alt="U">
        </a>
      </div>
      <div class="col-10">
        <div class="fabrx-social text-center text-md-right mt-3 mt-sm-0 float-end">
          <a href="https://www.linkedin.com/in/cyro-gondim-33168511b/" class="text-decoration-none  icon-social" style=" color: #0a66c2">
              <i class="fa-brands fa-linkedin"></i>
          </a>
          <a href="https://www.instagram.com/cyrogondim.corretor/" class="text-decoration-none icon-social" style="color: #c5007a">
              <i class="fa-brands fa-instagram"></i>
          </a>
        </div>
      </div>
    </div>
    <hr>
    <div class="container text-center">
      <span class="text-secondary ms-2">© 2022 Stark House</span>
    </div>
  </div>
</footer>